apiVersion: v1
kind: Service
metadata: 
  name: blockchain-service-http
  namespace: blockchain
spec: 
  selector: 
    app: blockchain-uniminuto
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
    targetPort: 8080
    name: svcserver
  type: NodePort
