apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  namespace: blockchain
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: blockchain-uniminuto
  template: 
    metadata:
      labels: 
        app: blockchain-uniminuto
    spec: 
      containers: 
      - name: blockchain-uniminuto-containerv1
        image: jfaragon/blockchain-umd:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 8080
          name: svcserver
        - containerPort: 6001
          name: listen-socket




