version: '2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
  node2:
    environment:
      - NODES=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8081:8080"
    links:
      - node1:node1
  node3:
    environment:
      - NODES=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8083:8080"
    links:
      - node2:node2
